version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: >-
    npm install gulp -g

    cd "ASP.NET Core with Angular\Web\PizzaDotNet.Web"

    npm install

    gulp build

    cd ..

    cd ..

    cd ..

    dotnet --version

    dotnet restore "ASP.NET Core with Angular/PizzaDotNet.sln"
build:
  project: ASP.NET Core with Angular/PizzaDotNet.sln
  verbosity: minimal